[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "pylast>=6.0.0",
    "spotipy>=2.25.1",
    "telegram>=0.0.1",
]
